# [[docs]]
#   name = "Prologue"
#   weight = 10
#   identifier = "prologue"
#   url = "/docs/prologue/"

# [[docs]]
#   name = "Help"
#   weight = 60
#   identifier = "help"
#   url = "/docs/help/"

# [[docs]]
#   name = "Lorem"
#   weight = 70
#   identifier = "lorem"
#   url = "/docs/lorem/"

# [[guide]]
#   name = "Lorem"
#   weight = 10
#   identifier = "lorem"
#   url = "/guide/lorem/"

# [[tutorial]]
#   name = "Lorem"
#   weight = 10
#   identifier = "lorem"
#   url = "/tutorial/lorem/"

[[main]]
  name = "SOLUTIONS"
  weight = 1
  identifier = "solutions"

[[main]]
  name = "API"
  weight = 2
  identifier = "api"
  url = "/docs/api/intro"

[[main]]
  name = "PARTNERS"
  weight = 3
  identifier = "partner-docs"
  url = "/docs/partner/intro"
  
  [[main]]
  name = "TROUBLESHOOTING"
  weight = 3
  identifier = "troubleshooting "
  url = "/docs/troubleshooting/intro"

[[main]]
  name = "RETAIL"
  weight = 10
  identifier = "retail"
  url = "/docs/retail/gettingstarted/intro" 
  parent = "solutions"

[[main]]
  name = "ATTRACTIONS"
  weight = 20
  identifier = "entertainment"
  url = "/docs/entertainment/intro"
  parent = "solutions"

[[main]]
  name = "HOSPITALITY"
  weight = 30
  identifier = "restaurant"
  url = "/docs/hospitality/intro"
  parent = "solutions"

[[main]]
  name = "WMS"
  weight = 40
  identifier = "wms"
  url = "/docs/wms/intro"
  parent = "solutions"

[[main]]
  name = "E-COMMERCE"
  weight = 50
  identifier = "ecommerce"
  url = "/docs/ecommerce/intro"
  parent = "solutions"

[[main]]
  name = "POWER BI"
  weight = 60
  identifier = "power-bi"
  url = "/docs/power_bi/intro"
  parent = "solutions"

[[main]]
  name = "FISCALIZATION"
  weight = 70
  identifier = "fiscalization"
  url = "/docs/fiscalization/intro"
  parent = "solutions"

[[main]]
  name = "NP PAY"
  weight = 80
  identifier = "providers"
  url = "/docs/np_pay/intro"
  parent = "solutions"

[[social]]
  name = "Linkedin"
  pre = '<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox="0 0 24 24" width="20" height="20" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="css-i6dzq1"><path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z"></path><rect x="2" y="9" width="4" height="12"></rect><circle cx="4" cy="4" r="2"></circle></svg>'
  url = "https://linkedin.com/company/navi-partner"
  weight = 10

[[social]]
  name = "Facebook"
  pre = '<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox="0 0 24 24" width="20" height="20" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="css-i6dzq1"><path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z"></path></svg>'
  url = "https://www.facebook.com/profile.php?id=100040012614456"
  weight = 20

[[social]]
  name = "YouTube"
  pre = '<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox="0 0 24 24" width="20" height="20" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="css-i6dzq1"><path d="M22.54 6.42a2.78 2.78 0 0 0-1.94-2C18.88 4 12 4 12 4s-6.88 0-8.6.46a2.78 2.78 0 0 0-1.94 2A29 29 0 0 0 1 11.75a29 29 0 0 0 .46 5.33A2.78 2.78 0 0 0 3.4 19c1.72.46 8.6.46 8.6.46s6.88 0 8.6-.46a2.78 2.78 0 0 0 1.94-2 29 29 0 0 0 .46-5.25 29 29 0 0 0-.46-5.33z"></path><polygon points="9.75 15.02 15.5 11.75 9.75 8.48 9.75 15.02"></polygon></svg>'
  url = "https://www.youtube.com/user/NaviPartnerKbh/videos"
  weight = 30

[[social]]
  name = "GitHub"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-github\"><path d=\"M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22\"></path></svg>"
  url = "https://github.com/navipartner/docs"
  post = "v0.1.0"
  weight = 40

# [[footer]]
#   name = "Privacy"
#   url = "/privacy-policy/"
#   weight = 10
